# Generated by Django 4.2 on 2023-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_phone_number_otpcode_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='wrong_code_enter_by_time',
            field=models.IntegerField(default=0),
        ),
    ]
