# Generated by Django 4.2 on 2023-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_otpcode_wrong_code_enter_by_time2'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
