# Generated by Django 4.2 on 2023-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_otpcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
