# Generated by Django 4.2 on 2023-04-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_otpcode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='wrong_code_enter_by_time2',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='wrong_code_enter_by_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
