# Generated by Django 4.2 on 2023-04-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_number_of_wrong_password_enter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='block_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
