# Generated by Django 4.2 on 2023-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp_code_remove_account_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_code',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
