# Generated by Django 4.2 on 2023-04-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_otp_code_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otp_code',
            new_name='OtpCode',
        ),
    ]
