# Generated by Django 4.2 on 2023-04-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_otp_code_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='wrong_code_enter_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
