# Generated by Django 4.2 on 2023-04-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_otpcode_wrong_code_enter_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='wrong_code_enter_time',
            new_name='wrong_code_enter_by_time',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='time_of_wrong_code_enter_by_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
