# Generated by Django 4.2 on 2023-04-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_otpcode_time_of_wrong_code_enter_by_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='user_block',
            field=models.BooleanField(default=False),
        ),
    ]
