# Generated by Django 4.2 on 2023-04-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_otpcode_user_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
